# Generated by Django 5.0 on 2023-12-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.IntegerField(choices=[(0, 'not started'), (1, 'started'), (2, 'ended')], default=0),
        ),
    ]
